name: jose manuel gomez
favicon: null
layout_spectrum: 0.50374
typography_spectrum: 0.477
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7a52e'
    - '#ba4039'
    - '#4b628d'
    - '#000000'
    - '#ffff00'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
